# Generated by Django 2.1.3 on 2018-11-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rickAndMorty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
