# Generated by Django 2.1.3 on 2018-11-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rickAndMorty', '0002_auto_20181126_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='image',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
